### ISSUE TITLE
Error every frame due to condition in spliced tree

### ISSUE THREAD

**Issue by PureSaltProductions** [ashblue/fluid-behavior-tree#15]
```
.Sequence("Die")
    .Condition("Should Die?", () => State.HasFlag(CharacterState.Dead))
    .PathfindingStop()
    .AnimancerCrossFade(AnimationDictionary.Animations["Die"])
.End()
//.Sequence("Die Tree")
//    .Splice(UnitTasks.Die(gameObject, this, AnimationDictionary.Animations["Die"]))
//.End()
```

**Comment by PureSaltProductions** [comment]
Error was found to be a rogue throw new System.NotImplementedException();

in
https://github.com/ashblue/fluid-behavior-tree/blob/master/Assets/FluidBehaviorTree/Runtime/TaskParents/TaskParentBase.cs#L44

**Comment by ashblue** [comment]
On it, will get a patch out today and a test to prevent future regressions.

**Comment by ashblue** [comment]
The bug has been patched. Please let me know if this fixes your issue https://github.com/ashblue/fluid-behavior-tree/releases/tag/v2.2.1

**Comment by PureSaltProductions** [comment]
Confirmed working in my environment

**Comment by ashblue** [comment]
@all-contributors please add @PureSaltProductions for userTesting
