### ISSUE TITLE
Minor editor rendering glitch

### ISSUE THREAD

**Issue by angstr0m** [ashblue/fluid-behavior-tree#29]
Thanks for this very nice behavior tree implementation! 

I found a minor cosmetic issue, which doesn't seem to affect the functionality or usability:

When rendering behavior trees in the editor, the horizontal lines are a bit off:
<img width="428" alt="grafik" src="https://user-images.githubusercontent.com/733176/94144105-05c86480-fe71-11ea-8407-600d1ef5bb10.png">

fluid-behavior-tree version: 2.2.2 (included using the Unity package manager)
Unity: 2019.4.10f1 Personal
OS: macOS 10.15.6

**Comment by ashblue** [comment]
Debating on fixing this or just rewriting things with the new UI 🤔 Will try to fix first though for sure.

**Comment by ashblue** [comment]
If somebody wants to track this down and fix it, I bet it's a single line bugging out.

**Comment by ashblue** [comment]
Fixed by PR #97
