### ISSUE TITLE
Wrong method invocation in base class ActionGeneric.cs

### ISSUE THREAD

**Issue by eLeSTRaGo-Dev** [ashblue/fluid-behavior-tree#35]
In script [ActionGeneric.cs](https://github.com/ashblue/fluid-behavior-tree/blob/develop/Assets/FluidBehaviorTree/Runtime/Tasks/Actions/ActionGeneric.cs) method `OnExit` call `initLogic` and `OnInit` call `exitLogic`.

```charp
protected override void OnExit () {
    initLogic?.Invoke();
}

protected override void OnInit () {
    exitLogic?.Invoke();
}
```

**Comment by ashblue** [comment]
Oh crap, that is definitely wrong. I'm not sure why I didn't get an email about this (or how I've been using this project and never noticed it). I'll get this fixed first thing tomorrow after work.

**Comment by ashblue** [comment]
@all-contributors please add @eLeSTRaGo-Dev for 🐛

**Comment by ashblue** [comment]
@all-contributors add @eLeSTRaGo-Dev for 🐛

**Comment by ashblue** [comment]
@all-contributors add @piotr-j for code

**Comment by ashblue** [comment]
@eLeSTRaGo-Dev it wont let me add you via all contributors, not sure why 🤔  Maybe privacy settings???

**Comment by ashblue** [comment]
Fixed. Travis CI was being a pain when I had to upgrade it (sorry for all the closed and re-opened tickets).

https://github.com/ashblue/fluid-behavior-tree/releases/tag/v2.2.3
