### ISSUE TITLE
share code with server

### ISSUE THREAD

**Issue by shanzhi666** [ashblue/fluid-behavior-tree#75]
our project have a online mode, we sperate our server code out of untiy view code. 
but fluid-BT uses GameObject as tree owner, i have to change all the owner type to implement this case.
can we change the owner  type as a interface?

**Comment by ashblue** [comment]
Does Unity provide an interface for the GameObject?  Last I checked they didn't provide something like that sadly. If they did provide one that would be a crazy easy change.

So the owner could be separated out to remove the Unity dependencies. But there would need to be an extra abstraction layer for the BT owner implementation with a generic and owner implementation override.

I'm guessing just passing null in for the GameObject won't fix it? Just wanna check to make sure.

**Comment by shanzhi666** [comment]
thanks, i'll check this one
