### ISSUE TITLE
TimeMonitor only works if Tick is called every frame

### ISSUE THREAD

**Issue by wilg** [ashblue/fluid-behavior-tree#76]
It does not seem like there is a way to call `Tick()` less than every frame, due to the way TimeMonitor just wraps `Time.deltaTime`. It seems like it should calculate the delta itself in this case.

**Comment by ashblue** [comment]
How exactly could it calculate the delta without knowing the previous frame though? You'd essentially have to do some caching on the current frame and check if it changed I believe. Open to implementation ideas here and pull requests are always welcome

**Comment by wilg** [comment]
Another design could be an overload of `Tick` that takes a `deltaTime` and it's internally passed to where it needs to be. Or Tick or a similar function could do its own bookkeeping. But the main issue that prevents a user of the library from handling this problem is the hardcoded TimeMonitors being created in the extension methods.

**Comment by ashblue** [comment]
I think the easiest way to change the implementation might be to allow an injectable interface that overrides the time calculations. ITimeManager or something like this.

```
interface ITimeManager {
  getTimePassed: () => float;
}
```

You would then have to create a custom implementation of the `TimeMonitorBase` probably and inject the interface. So with that much effort it feels like it might be easier to just create a custom action at that point. Let me know your thoughts.

**Comment by wilg** [comment]
Semi-related note: not updating every frame also causes the (great!) debugger window to flicker.

**Comment by ashblue** [comment]
Interesting. What version of Unity are you using? Don't think I've seen that behavior.

**Comment by ashblue** [comment]
Closing this one out since it would essentially require a new time block. Feel free to create a new PR or move this convo over to the discussions https://github.com/ashblue/fluid-behavior-tree/discussions
