### ISSUE TITLE
Logic mislead in TaskParentBase

### ISSUE THREAD

**Issue by eLeSTRaGo-Dev** [ashblue/fluid-behavior-tree#93]
In [TaskParentBase](https://github.com/ashblue/fluid-behavior-tree/blob/develop/Assets/com.fluid.behavior-tree/Runtime/TaskParents/TaskParentBase.cs) we have an End method, but this method does not execute. You can check this in [TaskParentTest](https://github.com/ashblue/fluid-behavior-tree/blob/develop/Assets/com.fluid.behavior-tree/Tests/Editor/TaskParents/TaskParentTest.cs).

So that produces an interesting case when you need to understand was a Parallel task completed. Because all tasks invoke End themselves.

```
Parallel:
    - ActionA (Success)
    - ActionB (Continue)
```

[Parallel](https://github.com/ashblue/fluid-behavior-tree/blob/develop/Assets/com.fluid.behavior-tree/Runtime/TaskParents/Composites/Parallel.cs) say us that End will be called when all tasks are completed. But in that case, ActionA call End at the same time us returns Success status.

**Comment by ashblue** [comment]
Haven't heard an update so closing this out. If the issue still isn't addressed happy to take another look at this
